# Copyright (c) 2024 Enflame. All Rights Reserved.

FROM tencentos/tencentos_server31:latest

ENV ENFLAME_VISIBLE_DEVICES=all
ENV ENFLAME_DRIVER_CAPABILITIES=utility

COPY ./config/topscloud.json /tmp/
COPY gcushare-device-plugin /usr/bin/gcushare-device-plugin

CMD ["gcushare-device-plugin"]
