# Copyright 2022 Enflame. All Rights Reserved.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcushare-device-plugin
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  verbs:
  - update
  - patch
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - update
  - patch
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcushare-device-plugin
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcushare-device-plugin 
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gcushare-device-plugin
subjects:
- kind: ServiceAccount
  name: gcushare-device-plugin
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gcushare-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
        component: gcushare-device-plugin
        app: gcushare
        name: gcushare-device-plugin-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: gcushare-device-plugin
        app: gcushare
        name: gcushare-device-plugin-ds
    spec:
      serviceAccount: gcushare-device-plugin
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/control-plane
      nodeSelector:
        enflame.com/gcushare: "true"
      containers:
      - image: artifact.enflame.cn/enflame_docker_images/enflame/gcushare-device-plugin:latest
        imagePullPolicy: IfNotPresent
        name: gcushare
        # Make this pod as Guaranteed pod which will never be evicted because of node's resource consumption.
        command:
          - gcushare-device-plugin
          - --slice-count=6
          - --resource-isolation=true
        resources:
          limits:
            memory: "300Mi"
            cpu: "1"
          requests:
            memory: "300Mi"
            cpu: "1"
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/kubelet.conf
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          # privileged: true
          # allowPrivilegeEscalation: false
          # capabilities:
          #   drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: gcushare-dic
            mountPath: /var/log/enflame/gcushare
          - name: topscloud-config
            mountPath: /etc/topscloud
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: gcushare-dic
          hostPath:
            path: /var/log/enflame/gcushare
            type: DirectoryOrCreate
        - name: topscloud-config
          hostPath:
            path: /etc/topscloud
            type: DirectoryOrCreate
