# Copyright (c) 2024 Enflame. All Rights Reserved.

FROM tencentos/tencentos_server31:latest AS builder

ARG VERSION
COPY binarys/${VERSION}/gcushare-scheduler-plugin /tmp/

FROM tencentos/tencentos_server31:latest

COPY --from=builder /tmp/gcushare-scheduler-plugin /usr/bin/
COPY ./config/topscloud.json /tmp/

CMD ["gcushare-scheduler-plugin"]
