# Copyright (c) 2024 Enflame. All Rights Reserved.

FROM ubuntu:18.04 AS builder

ARG VERSION
COPY binarys/${VERSION}/gcushare-scheduler-plugin /tmp/

FROM ubuntu:18.04

COPY --from=builder /tmp/gcushare-scheduler-plugin /usr/bin/
COPY ./config/topscloud.json /tmp/

CMD ["gcushare-scheduler-plugin"]
