# Copyright (c) 2024 Enflame. All Rights Reserved.

FROM openeuler/openeuler:20.03 AS builder

ARG VERSION
COPY binarys/${VERSION}/gcushare-scheduler-plugin /tmp/

FROM openeuler/openeuler:20.03

COPY --from=builder /tmp/gcushare-scheduler-plugin /usr/bin/
COPY ./config/topscloud.json /tmp/

CMD ["gcushare-scheduler-plugin"]
