# Copyright 2022 Enflame. All Rights Reserved.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.rbac.clusterRoleBinding.name }}  
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRole.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}